---
- hosts: primary_controller
  gather_facts: no
  vars_files:
    - config.cfg
    - ../windowsDC/tf_ansible_vars_file.yml
    - tf_ansible_vars_file.yml
    - api.yml
  vars:
    controller_api_url: "https://{{ tf_cnt1_public_ip }}:8443/admin"

  tasks:

  - name:  Wait for UI to come up
    wait_for:
      port: 8443
      state: started


  - name: Add Client Connection
    uri:
      url: "{{ controller_api_url }}/client-connections"
      method: PUT
      validate_certs: no
      body_format: json
      body: "{{ post_data | to_json }}"
      timeout: 10
      headers:
       Accept: "application/vnd.appgate.peer-v14+json"
       Authorization: "Bearer {{ apitoken }}"
    vars:
      post_data:
        spaMode: "TCP"
        profiles:
        - name: "Intranet Users"
          spaKeyName: "Lab-Key"
          identityProviderName: "Windows AD"
    register: result
    until: result.status == 200
    retries: 30
    delay: 10


  - name: Provide Client Profile Link
    debug: msg="   Use this URL to add the Client Profile to SDP   {{ result.json.profiles[0].url }}  "

  - name: Output to profile.txt
    delegate_to: localhost
    copy:
      content: "{{ result.json.profiles[0].url }}"
      dest: profile.txt



#  - name: Get QR Code
#    uri:
#      url: "{{ controller_api_url }}/client-connections/Intranet%20Users/barcode"
#      method: GET
#      validate_certs: no
#      body_format: json
#      body: "{}"
#      timeout: 10
#      headers:
#       Accept: "application/vnd.appgate.peer-v14+json"
#       Authorization: "Bearer {{ apitoken }}"
#    register: result
#    until: result.status == 200
#    retries: 30
#    delay: 10
#
#  - name: Dump
#    debug: msg="{{ result }}"
