---


#- include: install_python.yaml

- name: seed the appliance
  vars:
    auth_key_inline: "{{ auth_key_content }}"
    target_hostname: "{{ fqdn }}"
  template:
    src: seed.j2
    dest: /home/cz/seed.json
    owner: cz
    mode: 644

- name:  Wait for UI to come up
  wait_for:
    port: 8443
    state: started


# - name: Pause for 3 minutes to catch up
#   pause:
#     minutes: 3

#- name: reboot appliance
#  become: true
#  become_user: root
#  become_method: sudo
#  reboot:
